"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { Download, FileText, Loader2, Plus, Trash2, Upload } from "lucide-react";
import { ApiClientError } from "@codementor/api-client";
import { Select, useToast } from "@codementor/ui";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { ConfirmDialog } from "@/components/ui/confirm-dialog";
import { Pagination } from "@/components/ui/pagination";
import { api } from "@/lib/api";
import type { ExerciseSummary } from "@/types/catalogue";
import type { WorkspaceAssignment, WorkspaceContentPage, WorkspaceDetail, WorkspaceDocument, WorkspaceExercise, WorkspaceMember } from "../types";

const EMPTY_PAGE = <T,>(): WorkspaceContentPage<T> => ({ items: [], page: 1, limit: 12, total: 0, totalPages: 0 });
const inputClass = "rounded-md border border-border bg-surface px-3 py-2 text-sm text-navy";

export function WorkspaceDocumentsTab({ detail }: { detail: WorkspaceDetail }) {
  const toast = useToast();
  const [data, setData] = useState(EMPTY_PAGE<WorkspaceDocument>());
  const [page, setPage] = useState(1); const [q, setQ] = useState(""); const [status, setStatus] = useState("");
  const [loading, setLoading] = useState(true); const [uploading, setUploading] = useState(false); const [progress, setProgress] = useState(0); const [removing, setRemoving] = useState<WorkspaceDocument | null>(null);
  const canUpload = detail.currentMembership.role === "owner" || detail.currentMembership.permissions.upload_doc;
  const canManage = detail.currentMembership.role === "owner" || detail.currentMembership.permissions.delete_doc;
  const load = useCallback(async () => { setLoading(true); try { setData(await api.workspaces.documents(detail.slug, { page, limit: 12, q: q || undefined, status: status || undefined })); } catch (e) { toast.error(messageOf(e)); } finally { setLoading(false); } }, [detail.slug, page, q, status, toast]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 250); return () => window.clearTimeout(timer); }, [load]);

  const upload = async (file: File) => { setUploading(true); setProgress(0); try { const config = await api.workspaces.documentUploadConfig(detail.slug); if (!config.enabled) throw new Error("Storage chưa được cấu hình"); if (!config.acceptedTypes.includes(file.type) || file.size > config.maxBytes) throw new Error("Định dạng hoặc dung lượng tệp không hợp lệ"); const signed = await api.workspaces.documentUploadUrl(detail.slug, { filename: file.name, contentType: file.type, sizeBytes: file.size }); await putFile(signed.uploadUrl, signed.headers, file, setProgress); await api.workspaces.createDocument(detail.slug, { filename: file.name, contentType: file.type, sizeBytes: file.size, title: file.name.replace(/\.[^.]+$/, ""), docType: extension(file.name), storageKey: signed.objectKey, url: signed.publicUrl }); toast.success("Đã tải tài liệu lên"); await load(); } catch (e) { toast.error(messageOf(e)); } finally { setUploading(false); setProgress(0); } };
  const remove = async () => { if (!removing) return; try { await api.workspaces.deleteDocument(detail.slug, removing.id); toast.success("Đã xóa tài liệu"); setRemoving(null); await load(); } catch (e) { toast.error(messageOf(e)); } };
  const changeStatus = async (doc: WorkspaceDocument, next: string) => { try { await api.workspaces.updateDocument(detail.slug, doc.id, { status: next }); await load(); } catch (e) { toast.error(messageOf(e)); } };
  return <div className="space-y-4">
    <div className="flex flex-wrap items-center gap-2"><input className={`${inputClass} min-w-56 flex-1`} placeholder="Tìm tài liệu..." value={q} onChange={(e) => { setQ(e.target.value); setPage(1); }} /><Select label="Trạng thái" value={status} onChange={(v) => { setStatus(v); setPage(1); }} options={[{ value: "", label: "Tất cả" }, { value: "published", label: "Đã duyệt" }, { value: "pending", label: "Chờ duyệt" }, { value: "hidden", label: "Đã ẩn" }]} />{canUpload && <label className="inline-flex cursor-pointer items-center gap-2 rounded-md bg-primary px-3 py-2 text-xs font-semibold text-on-ink"><Upload className="h-3.5 w-3.5" />{uploading ? `Đang tải ${progress}%` : "Tải tài liệu"}<input type="file" className="sr-only" disabled={uploading} accept=".pdf,.doc,.docx,.ppt,.pptx,.xls,.xlsx,.txt,.png,.jpg,.jpeg,.webp" onChange={(e) => { const file = e.target.files?.[0]; if (file) void upload(file); e.target.value = ""; }} /></label>}</div>
    {loading ? <Loading /> : data.items.length === 0 ? <Empty icon={FileText} title="Chưa có tài liệu" /> : <div className="grid gap-3">{data.items.map((doc) => <Card key={doc.id} className="flex flex-wrap items-center gap-3 p-4"><FileText className="h-5 w-5 text-text-faint" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-navy">{doc.title}</p><p className="text-xs text-text-faint">{doc.docType} · {doc.uploaderName ?? "Không rõ"} · {formatDate(doc.uploadedAt)}</p></div><span className="text-xs font-medium text-text-muted">{statusLabel(doc.status)}</span>{doc.url && <Button href={doc.url} target="_blank" size="sm" variant="outline"><Download className="h-3.5 w-3.5" />Xem</Button>}{canManage && <><Select label="Duyệt" value={doc.status} onChange={(v) => void changeStatus(doc, v)} options={[{ value: "published", label: "Đã duyệt" }, { value: "pending", label: "Chờ duyệt" }, { value: "hidden", label: "Ẩn" }, { value: "rejected", label: "Từ chối" }]} /><Button size="sm" variant="outline" onClick={() => setRemoving(doc)}><Trash2 className="h-3.5 w-3.5" />Xóa</Button></>}</Card>)}</div>}
    <Pagination page={page} pageCount={data.totalPages} onChange={setPage} label="Phân trang tài liệu" />
    <ConfirmDialog open={removing !== null} onClose={() => setRemoving(null)} onConfirm={() => void remove()} title="Xóa tài liệu?" confirmLabel="Xóa" message={`Tệp “${removing?.title ?? ""}” sẽ bị xóa khỏi database và storage.`} />
  </div>;
}

export function WorkspaceExercisesTab({ detail, members }: { detail: WorkspaceDetail; members: WorkspaceMember[] }) {
  const toast = useToast(); const [data, setData] = useState(EMPTY_PAGE<WorkspaceExercise>()); const [bank, setBank] = useState<ExerciseSummary[]>([]); const [page, setPage] = useState(1); const [q, setQ] = useState(""); const [difficulty, setDifficulty] = useState(""); const [selected, setSelected] = useState(""); const [dueAt, setDueAt] = useState(""); const [busy, setBusy] = useState(false); const [removing, setRemoving] = useState<WorkspaceExercise | null>(null);
  const canCreate = detail.currentMembership.role === "owner" || detail.currentMembership.permissions.create_exercise; const canEdit = detail.currentMembership.role === "owner" || detail.currentMembership.permissions.edit_exercise;
  const load = useCallback(async () => { try { setData(await api.workspaces.workspaceExercises(detail.slug, { page, limit: 12, q: q || undefined, difficulty: difficulty || undefined })); } catch (e) { toast.error(messageOf(e)); } }, [detail.slug, page, q, difficulty, toast]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 250); return () => window.clearTimeout(timer); }, [load]);
  useEffect(() => { if (canCreate) void api.exercises.bank({ limit: 50 }).then((r) => setBank(r.items)).catch(() => setBank([])); }, [canCreate]);
  const attach = async () => { if (!selected) return; setBusy(true); try { await api.workspaces.attachExercise(detail.slug, { exerciseId: selected, dueAt: dueAt ? new Date(dueAt).toISOString() : undefined, memberIds: members.filter((m) => m.role !== "owner").map((m) => m.id) }); toast.success("Đã thêm và phân công bài tập"); setSelected(""); setDueAt(""); await load(); } catch (e) { toast.error(messageOf(e)); } finally { setBusy(false); } };
  const remove = async () => { if (!removing) return; try { await api.workspaces.deleteWorkspaceExercise(detail.slug, removing.id); setRemoving(null); await load(); } catch (e) { toast.error(messageOf(e)); } };
  return <div className="space-y-4">{canCreate && <Card className="flex flex-wrap items-end gap-3 p-4"><Select label="Bài tập từ kho công khai" value={selected} onChange={setSelected} options={[{ value: "", label: "Chọn bài tập" }, ...bank.map((x) => ({ value: x.id, label: x.title }))]} /><label className="text-xs font-medium text-text-muted">Hạn nộp<input type="datetime-local" className={`mt-1 block ${inputClass}`} value={dueAt} onChange={(e) => setDueAt(e.target.value)} /></label><Button size="sm" disabled={!selected || busy} onClick={() => void attach()}><Plus className="h-3.5 w-3.5" />Thêm và giao</Button></Card>}<div className="flex gap-2"><input className={`${inputClass} flex-1`} placeholder="Tìm bài tập..." value={q} onChange={(e) => { setQ(e.target.value); setPage(1); }} /><Select label="Độ khó" value={difficulty} onChange={(v) => { setDifficulty(v); setPage(1); }} options={[{ value: "", label: "Tất cả" }, { value: "easy", label: "Cơ bản" }, { value: "medium", label: "Trung bình" }, { value: "hard", label: "Nâng cao" }]} /></div>{data.items.length === 0 ? <Empty icon={Plus} title="Chưa có bài tập" /> : <div className="grid gap-3">{data.items.map((ex) => <Card key={ex.id} className="flex flex-wrap items-center gap-3 p-4"><div className="min-w-0 flex-1"><p className="font-semibold text-navy">{ex.title}</p><p className="text-xs text-text-faint">{difficultyLabel(ex.difficulty)} · {ex.completedCount}/{ex.assignedCount} hoàn thành · {ex.dueAt ? formatDate(ex.dueAt) : "Không hạn"}</p></div><Button href={`/solve/${ex.exerciseId}`} size="sm" variant="outline">Mở bài</Button>{canEdit && <Button size="sm" variant="outline" onClick={() => setRemoving(ex)}><Trash2 className="h-3.5 w-3.5" />Gỡ</Button>}</Card>)}</div>}<Pagination page={page} pageCount={data.totalPages} onChange={setPage} label="Phân trang bài tập" /><ConfirmDialog open={removing !== null} onClose={() => setRemoving(null)} onConfirm={() => void remove()} title="Gỡ bài tập khỏi nhóm?" confirmLabel="Gỡ" message={`Các assignment chưa có bài nộp của “${removing?.title ?? ""}” sẽ bị xóa.`} /></div>;
}

export function WorkspaceAssignmentsTab({ detail }: { detail: WorkspaceDetail }) {
  const toast = useToast(); const [data, setData] = useState(EMPTY_PAGE<WorkspaceAssignment>()); const [page, setPage] = useState(1); const [q, setQ] = useState(""); const [status, setStatus] = useState(""); const canReview = detail.currentMembership.role === "owner" || detail.currentMembership.permissions.review_submission;
  const load = useCallback(async () => { try { setData(await api.workspaces.assignments(detail.slug, { page, limit: 12, q: q || undefined, status: status || undefined })); } catch (e) { toast.error(messageOf(e)); } }, [detail.slug, page, q, status, toast]); useEffect(() => { const timer = window.setTimeout(() => void load(), 250); return () => window.clearTimeout(timer); }, [load]);
  const update = async (item: WorkspaceAssignment, body: { status?: string; reviewStatus?: string }) => { try { await api.workspaces.updateAssignment(detail.slug, item.id, body); await load(); } catch (e) { toast.error(messageOf(e)); } };
  return <div className="space-y-4"><div className="flex gap-2"><input className={`${inputClass} flex-1`} placeholder="Tìm bài hoặc thành viên..." value={q} onChange={(e) => { setQ(e.target.value); setPage(1); }} /><Select label="Trạng thái" value={status} onChange={(v) => { setStatus(v); setPage(1); }} options={[{ value: "", label: "Tất cả" }, { value: "notstarted", label: "Chưa bắt đầu" }, { value: "inprogress", label: "Đang làm" }, { value: "done", label: "Đã xong" }, { value: "late", label: "Trễ hạn" }]} /></div>{data.items.length === 0 ? <Empty icon={FileText} title="Chưa có bài được giao" /> : <div className="grid gap-3">{data.items.map((item) => <Card key={item.id} className="flex flex-wrap items-center gap-3 p-4"><div className="min-w-0 flex-1"><p className="font-semibold text-navy">{item.exerciseTitle}</p><p className="text-xs text-text-faint">{item.memberName} · {assignmentLabel(item.status)} · {item.submissionCount} lượt nộp{item.latestAttemptNumber ? ` · lần gần nhất #${item.latestAttemptNumber}` : ""}</p>{item.latestVerdict && <p className="mt-1 text-xs text-text-muted">{verdictLabel(item.latestVerdict)}{item.latestScore !== null ? ` · ${item.latestScore}/100 điểm` : ""}{item.latestIsLate ? " · nộp trễ" : ""}{item.latestSubmittedAt ? ` · ${formatDate(item.latestSubmittedAt)}` : ""}</p>}</div><Link className="text-xs font-semibold text-primary" href={canReview ? `/solve/${item.exerciseId}` : `/solve/${item.exerciseId}?assignmentId=${item.id}`}>{canReview ? "Xem đề" : "Làm bài"}</Link>{canReview ? <Select label="Duyệt" value={item.reviewStatus} onChange={(v) => void update(item, { reviewStatus: v })} options={[{ value: "pending", label: "Chờ duyệt" }, { value: "approved", label: "Đạt" }, { value: "needsfix", label: "Cần sửa" }]} /> : item.status === "done" || item.status === "late" ? <span className="text-xs font-semibold text-success">Cập nhật từ bài nộp</span> : <Select label="Tiến độ" value={item.status} onChange={(v) => void update(item, { status: v })} options={[{ value: "notstarted", label: "Chưa bắt đầu" }, { value: "inprogress", label: "Đang làm" }]} />}</Card>)}</div>}<Pagination page={page} pageCount={data.totalPages} onChange={setPage} label="Phân trang bài nộp" /></div>;
}

function Loading() { return <div className="flex justify-center p-10"><Loader2 className="h-5 w-5 animate-spin text-primary" /></div>; }
function Empty({ icon: Icon, title }: { icon: typeof FileText; title: string }) { return <Card className="border-dashed p-8 text-center"><Icon className="mx-auto h-6 w-6 text-text-faint" /><p className="mt-2 text-sm font-semibold text-navy">{title}</p></Card>; }
function messageOf(error: unknown) { return error instanceof ApiClientError ? error.message : error instanceof Error ? error.message : "Có lỗi xảy ra"; }
function formatDate(value: string) { return new Intl.DateTimeFormat("vi-VN", { dateStyle: "short", timeStyle: "short" }).format(new Date(value)); }
function extension(name: string) { return name.split(".").pop()?.toUpperCase() || "FILE"; }
function statusLabel(value: string) { return ({ published: "Đã duyệt", pending: "Chờ duyệt", hidden: "Đã ẩn", rejected: "Từ chối", changes: "Cần sửa" } as Record<string, string>)[value] ?? value; }
function difficultyLabel(value: string) { return ({ easy: "Cơ bản", medium: "Trung bình", hard: "Nâng cao" } as Record<string, string>)[value] ?? value; }
function assignmentLabel(value: string) { return ({ notstarted: "Chưa bắt đầu", inprogress: "Đang làm", done: "Đã xong", late: "Trễ hạn" } as Record<string, string>)[value] ?? value; }
function verdictLabel(value: string) { return ({ accepted: "Đạt", wrong_answer: "Sai kết quả", compile_error: "Lỗi biên dịch", runtime_error: "Lỗi thực thi", timeout: "Quá thời gian", memory_exceeded: "Quá bộ nhớ", pending: "Đang chấm" } as Record<string, string>)[value] ?? value; }
function putFile(url: string, headers: Record<string, string>, file: File, progress: (value: number) => void) { return new Promise<void>((resolve, reject) => { const request = new XMLHttpRequest(); request.open("PUT", url); Object.entries(headers).forEach(([key, value]) => request.setRequestHeader(key, value)); request.upload.onprogress = (event) => { if (event.lengthComputable) progress(Math.round((event.loaded / event.total) * 100)); }; request.onload = () => request.status >= 200 && request.status < 300 ? resolve() : reject(new Error(`Storage trả ${request.status}`)); request.onerror = () => reject(new Error("Không kết nối được storage")); request.send(file); }); }
