"use client";

import { useState } from "react";
import { Check, ChevronDown, ChevronUp, ClipboardCheck, FileWarning, Play, Send, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { SideDrawer } from "@/components/ui/side-drawer";
import { EXERCISE_STATUS_META } from "@/lib/study-group/group-detail-meta";
import type { GroupExercise } from "@/types/study-group-detail";

type ReviewDecision = "published" | "changes_requested" | "rejected";

export function ExerciseReviewQueue({ exercises, onDecision }: { exercises: GroupExercise[]; onDecision: (id: string, decision: ReviewDecision, note: string) => void }) {
  const [selected, setSelected] = useState<GroupExercise | null>(null);
  const [expanded, setExpanded] = useState(true);
  const waiting = exercises.filter((exercise) => exercise.status === "pending_review" || exercise.status === "changes_requested");
  if (waiting.length === 0) return null;
  return <section className="mb-5 rounded-xl border border-border bg-surface p-4"><div className="flex items-center justify-between gap-3"><div><h2 className="flex items-center gap-2 text-base font-bold text-navy"><ClipboardCheck className="h-4 w-4 text-primary" /> Bài tập chờ duyệt <span className="rounded-full bg-primary px-2 py-0.5 text-2xs text-on-ink">{waiting.length}</span></h2><p className="mt-1 text-xs text-text-faint">Bài do thành viên gửi chỉ xuất hiện cho cả nhóm sau khi được phê duyệt.</p></div><button type="button" aria-expanded={expanded} onClick={() => setExpanded((value) => !value)} className="flex h-8 w-8 shrink-0 items-center justify-center rounded-md border border-border text-text-muted hover:bg-bg hover:text-navy" title={expanded ? "Thu gọn danh sách chờ duyệt" : "Mở danh sách chờ duyệt"}>{expanded ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}</button></div>{expanded && <div className="mt-4 grid gap-3 sm:grid-cols-2">{waiting.map((exercise) => <Card key={exercise.id} className="flex flex-col gap-3 p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h3 className="truncate font-semibold text-navy">{exercise.title}</h3><p className="mt-1 text-xs text-text-faint">{exercise.authorName} · gửi {exercise.reviewRequestedAt ?? exercise.createdAt}</p></div><Badge tone="primary">{EXERCISE_STATUS_META[exercise.status].label}</Badge></div><p className="line-clamp-2 text-xs leading-relaxed text-text-muted">{exercise.objective}</p><div className="flex flex-wrap gap-x-3 text-xs text-text-faint"><span>{exercise.difficulty}</span><span>{exercise.topic}</span><span>{exercise.testCaseCount ?? 0} test</span></div><Button size="sm" variant="outline" onClick={() => setSelected(exercise)}>Mở để duyệt</Button></Card>)}</div>}<ExerciseReviewDrawer exercise={selected} onClose={() => setSelected(null)} onDecision={onDecision} /></section>;
}

function ExerciseReviewDrawer({ exercise, onClose, onDecision }: { exercise: GroupExercise | null; onClose: () => void; onDecision: (id: string, decision: ReviewDecision, note: string) => void }) {
  const [decision, setDecision] = useState<ReviewDecision | null>(null);
  const [note, setNote] = useState("");
  if (!exercise) return null;
  const needsReason = decision === "changes_requested" || decision === "rejected";
  const submit = () => { if (!decision || (needsReason && !note.trim())) return; onDecision(exercise.id, decision, note.trim()); onClose(); };
  return <SideDrawer open onClose={onClose} title={`Duyệt: ${exercise.title}`} description="Kiểm tra nội dung, test case và mức độ phù hợp trước khi công bố cho nhóm." footer={<><Button size="sm" variant="outline" onClick={onClose}>Đóng</Button>{decision ? <Button size="sm" disabled={needsReason && !note.trim()} onClick={submit}>{decision === "published" ? "Phê duyệt & công bố" : decision === "rejected" ? "Từ chối bài tập" : "Gửi yêu cầu chỉnh sửa"}</Button> : <Button size="sm" variant="outline" onClick={() => setDecision("published")}><Check className="h-3.5 w-3.5" /> Phê duyệt</Button>}</>}>
    <div className="space-y-5"><div className="flex flex-wrap gap-2"><Badge tone="primary">{EXERCISE_STATUS_META[exercise.status].label}</Badge><span className="text-xs text-text-faint">{exercise.authorName} · {exercise.reviewRequestedAt ?? exercise.createdAt}</span></div><Card className="p-4"><h3 className="mb-2 text-sm font-bold text-navy">Mô tả của người tạo</h3><p className="text-sm leading-relaxed text-text">{exercise.creatorNote ?? "Không có ghi chú bổ sung."}</p></Card><section><h3 className="mb-2 text-sm font-bold text-navy">Đề bài</h3><p className="text-sm leading-relaxed text-text">{exercise.objective}</p></section><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[{ label: "Ngôn ngữ", value: exercise.supportLanguages?.join(", ") ?? "Chưa đặt" }, { label: "Test case", value: String(exercise.testCaseCount ?? 0) }, { label: "Thời gian", value: exercise.timeLimit ?? "–" }, { label: "Bộ nhớ", value: exercise.memoryLimit ?? "–" }].map((item) => <Card key={item.label} className="p-3"><div className="text-xs text-text-faint">{item.label}</div><div className="mt-1 text-xs font-semibold text-navy">{item.value}</div></Card>)}</div><section><h3 className="mb-2 text-sm font-bold text-navy">Ví dụ và ràng buộc</h3><pre className="overflow-x-auto rounded-md bg-bg p-3 text-xs text-text"><strong>Input:</strong> {exercise.sampleInput}{"\n"}<strong>Output:</strong> {exercise.sampleOutput}</pre><ul className="mt-3 list-disc space-y-1 pl-4 text-sm text-text">{exercise.constraints?.map((constraint) => <li key={constraint}>{constraint}</li>)}</ul></section><Card className="border-dashed p-4"><div className="flex items-center gap-2 text-sm font-semibold text-navy"><Play className="h-4 w-4 text-primary" /> Kiểm tra mẫu</div><p className="mt-1 text-xs text-text-faint">Mock runner: {exercise.testCaseCount ?? 0}/{exercise.testCaseCount ?? 0} test case mẫu cho expected output hợp lệ.</p></Card>{decision && decision !== "published" && <div><label htmlFor="review-note" className="mb-1.5 flex items-center gap-1.5 text-xs font-semibold text-navy"><FileWarning className="h-3.5 w-3.5 text-primary" /> Lý do phản hồi <span className="text-primary">*</span></label><textarea id="review-note" value={note} onChange={(event) => setNote(event.target.value)} rows={4} placeholder="Nêu rõ phần cần chỉnh sửa hoặc lý do từ chối..." className="w-full rounded-md border border-border bg-surface px-3 py-2 text-sm text-navy outline-none focus:border-navy" /></div>} {!decision && <div className="grid gap-2 sm:grid-cols-2"><Button size="sm" variant="outline" onClick={() => setDecision("changes_requested")}><Send className="h-3.5 w-3.5" /> Yêu cầu chỉnh sửa</Button><Button size="sm" variant="outline" className="text-primary" onClick={() => setDecision("rejected")}><X className="h-3.5 w-3.5" /> Từ chối</Button></div>}</div>
  </SideDrawer>;
}
